### ISSUE TITLE
Script support and maintenance

### ISSUE THREAD

**Issue by ribeiroeder** [mdz-repos/mr-image-resize#8]
Hello @mendezcode

First of all I want to thank you for all the work you have been developing for the open source wordpress community. 

Currently I use in over 50 sites (php 7.4) that I produced your mr-image-resize php script (Native WordPress Image Processing Library), it always worked perfectly, I consider it an incredible script.

My big concern is that it has not received any updates since 2014, so I’d like to ask if I can continue using it without fear. All other “resize on the fly” scripts are much lower than what you have developed, and I wish I could continue to use it for several more years!

Thank you and I would be very happy (and relieved) if you can answer me.

**Comment by mendezcode** [comment]
Hello @ribeiroeder!

My apologies for the delay getting back to you. Over the past few years I haven't had the chance to update the script, honestly I had no idea people even used it! :)

Since the plugin only uses WordPress core functions, you are on the safe side (this means, it is stable and tested). If it's working now, it will continue to work until it breaks, or more specifically, when these core functions change. And when that happens, please add an issue here or send me an email to mendezcode at gmail dot com.

I have also taken the time to do a security audit on the code, and everything is good ✔️ 

That being said, it should be okay to continue running the code on your sites ✔️ 

Hope that helps with some peace of mind (hehe! I know how it feels).

Cheers

**Comment by ribeiroeder** [comment]
Coming back to inform that I have been using the script with php8.1 and it has been working perfectly and without error_log. Thanks!
